# ==========================================
# 1. ビルド用ステージ（重い環境でビルドする）
# ==========================================
FROM golang:1.25-bookworm AS builder

WORKDIR /app

# Go Workspace の設定ファイル群をコピー
COPY go.work go.work.sum ./
COPY backend/go.mod backend/go.sum ./backend/
COPY gen/go.mod gen/go.sum ./gen/

#キャッシュマウント
RUN --mount=type=cache,target=/go/pkg/mod \
    cd backend && go mod download
RUN --mount=type=cache,target=/go/pkg/mod \
    cd gen && go mod download

# 依存パッケージのダウンロード
RUN cd backend && go mod download
RUN cd gen && go mod download

# ソースコード全体をコピー
COPY backend/ ./backend/
COPY gen/ ./gen/

#モジュールキャッシュを再利用して、コード生成とビルドを行う
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /server ./cmd/server/main.go

# 完全な静的バイナリとしてビルド（CGO_ENABLED=0 が Distroless で動かすための鍵）
WORKDIR /app/backend
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /server ./cmd/server/main.go

# ==========================================
# 2. 実行用ステージ（Distrolessで軽く・安全に動かす）
# ==========================================
FROM gcr.io/distroless/static-debian12

# ビルド用ステージで作った実行ファイルだけをコピー
COPY --from=builder /server /server

# root権限を持たない安全なユーザーで実行
USER nonroot:nonroot

EXPOSE 8080

# 実行時のカレントディレクトリを /tmp に変更
# （これだけで、アプリは書き込み可能な /tmp 内に controls.bleve を作ります）
WORKDIR /tmp

# 実行コマンド
ENTRYPOINT ["/server"]



