apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-ksa
  annotations:
    iam.gke.io/gcp-service-account: backend-sa@welcome-study-sakamoto.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-ksa
      volumes:
        - name: bleve-index-volume
          persistentVolumeClaim:
            claimName: bleve-index-pvc
      initContainers:
        - name: fix-permissions
          image: busybox
          command: 
            - sh
            - -c
            - |
              chown -R 65532:65532 /tmp/bleve-data
          volumeMounts:
            - name: bleve-index-volume
              mountPath: /tmp/bleve-data
      
      containers:
        - name: backend
          image: asia-northeast1-docker.pkg.dev/welcome-study-sakamoto/security-check-repo/backend:v15
          volumeMounts:
            - name: bleve-index-volume
              mountPath: /tmp/bleve-data
          
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
          env:
            - name: BLEVE_INDEX_PATH
              value: "/tmp/bleve-data/controls.bleve"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DATABASE_URL
              value: "postgres://postgres:$(DB_PASSWORD)@127.0.0.1:5432/security_check?sslmode=disable"
              
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
              cpu: "100m"
          args:
          - "--port=5432"
          - "welcome-study-sakamoto:asia-northeast1:security-check-db-instance"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http-backend": "backend-hc-config"}}'
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - name: http-backend
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bleve-index-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



      
     

       
        