apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-ksa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: "frontend-sa@welcome-study-sakamoto.iam.gserviceaccount.com"
---    
# k8s/frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-ksa
      containers:
      - name: frontend
        image: asia-northeast1-docker.pkg.dev/welcome-study-sakamoto/security-check-repo/frontend:v22
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
        env:
        # フロントエンドからバックエンド（Service名）への通信先
        - name: API_URL
          value: "http://backend:8080"
        - name: NEXT_PUBLIC_API_URL
          value: "https://anywhere-wwd.com"
        - name: GCP_BUCKET_NAME
          value: "welcome-study-sakamoto-bucket"
        # NextAuth 設定
        - name: NEXTAUTH_URL
          value: "https://anywhere-wwd.com"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: nextauth-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: nextauth-secret
              key: GOOGLE_CLIENT_SECRET
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: nextauth-secret
              key: NEXTAUTH_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    cloud.google.com/backend-config: '{"default": "my-security-config"}'
  
spec:
  
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000