// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: controls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countControls = `-- name: CountControls :one
SELECT COUNT(*) FROM controls
`

func (q *Queries) CountControls(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countControls)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingUnmatchedTasks = `-- name: CountPendingUnmatchedTasks :one
SELECT COUNT(*) FROM unmatched_tasks WHERE status = 'pending'
`

func (q *Queries) CountPendingUnmatchedTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingUnmatchedTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentTeamUpdates = `-- name: CountRecentTeamUpdates :one
SELECT COUNT(*) FROM feed_events 
WHERE created_at >= NOW() - INTERVAL '7 days'
`

func (q *Queries) CountRecentTeamUpdates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentTeamUpdates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createControl = `-- name: CreateControl :one
INSERT INTO controls (
  id, title, question, answer, category, status, version, tags, updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, title, question, answer, category, tags, version, updated_by, updated_at, status
`

type CreateControlParams struct {
	ID        string            `json:"id"`
	Title     string            `json:"title"`
	Question  string            `json:"question"`
	Answer    string            `json:"answer"`
	Category  string            `json:"category"`
	Status    NullControlStatus `json:"status"`
	Version   int32             `json:"version"`
	Tags      []string          `json:"tags"`
	UpdatedBy string            `json:"updated_by"`
}

func (q *Queries) CreateControl(ctx context.Context, arg CreateControlParams) (Control, error) {
	row := q.db.QueryRow(ctx, createControl,
		arg.ID,
		arg.Title,
		arg.Question,
		arg.Answer,
		arg.Category,
		arg.Status,
		arg.Version,
		arg.Tags,
		arg.UpdatedBy,
	)
	var i Control
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Question,
		&i.Answer,
		&i.Category,
		&i.Tags,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const createControlVersion = `-- name: CreateControlVersion :one
INSERT INTO control_versions (
    control_id, version, snapshot, diff, changed_by
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING control_id, version, snapshot, diff, changed_by, changed_at
`

type CreateControlVersionParams struct {
	ControlID string `json:"control_id"`
	Version   int32  `json:"version"`
	Snapshot  []byte `json:"snapshot"`
	Diff      []byte `json:"diff"`
	ChangedBy string `json:"changed_by"`
}

// 変更前のスナップショットと差分をJSONで保存するためのクエリです
func (q *Queries) CreateControlVersion(ctx context.Context, arg CreateControlVersionParams) (ControlVersion, error) {
	row := q.db.QueryRow(ctx, createControlVersion,
		arg.ControlID,
		arg.Version,
		arg.Snapshot,
		arg.Diff,
		arg.ChangedBy,
	)
	var i ControlVersion
	err := row.Scan(
		&i.ControlID,
		&i.Version,
		&i.Snapshot,
		&i.Diff,
		&i.ChangedBy,
		&i.ChangedAt,
	)
	return i, err
}

const deleteControl = `-- name: DeleteControl :exec
DELETE FROM controls
WHERE id = $1
`

func (q *Queries) DeleteControl(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteControl, id)
	return err
}

const getControl = `-- name: GetControl :one
SELECT 
    id, title, category, question, answer, status, version, tags, updated_by, updated_at
FROM controls
WHERE id = $1
`

type GetControlRow struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Question  string             `json:"question"`
	Answer    string             `json:"answer"`
	Status    NullControlStatus  `json:"status"`
	Version   int32              `json:"version"`
	Tags      []string           `json:"tags"`
	UpdatedBy string             `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetControl(ctx context.Context, id string) (GetControlRow, error) {
	row := q.db.QueryRow(ctx, getControl, id)
	var i GetControlRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Question,
		&i.Answer,
		&i.Status,
		&i.Version,
		&i.Tags,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getControlsByIDs = `-- name: GetControlsByIDs :many
SELECT 
    id, title, category, question, answer, status, version, tags, updated_by, updated_at
FROM controls
WHERE id = ANY($1::varchar[])
ORDER BY updated_at DESC
`

type GetControlsByIDsRow struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Question  string             `json:"question"`
	Answer    string             `json:"answer"`
	Status    NullControlStatus  `json:"status"`
	Version   int32              `json:"version"`
	Tags      []string           `json:"tags"`
	UpdatedBy string             `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetControlsByIDs(ctx context.Context, dollar_1 []string) ([]GetControlsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getControlsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetControlsByIDsRow
	for rows.Next() {
		var i GetControlsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.Status,
			&i.Version,
			&i.Tags,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControls = `-- name: ListControls :many
SELECT
    id, title, category, question, answer, status, version, tags, updated_by, updated_at
FROM controls
ORDER BY updated_at DESC
`

type ListControlsRow struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Question  string             `json:"question"`
	Answer    string             `json:"answer"`
	Status    NullControlStatus  `json:"status"`
	Version   int32              `json:"version"`
	Tags      []string           `json:"tags"`
	UpdatedBy string             `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListControls(ctx context.Context) ([]ListControlsRow, error) {
	rows, err := q.db.Query(ctx, listControls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlsRow
	for rows.Next() {
		var i ListControlsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.Status,
			&i.Version,
			&i.Tags,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlsPaginated = `-- name: ListControlsPaginated :many
SELECT
    id, title, category, question, answer, status, version, tags, updated_by, updated_at
FROM controls
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListControlsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListControlsPaginatedRow struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Question  string             `json:"question"`
	Answer    string             `json:"answer"`
	Status    NullControlStatus  `json:"status"`
	Version   int32              `json:"version"`
	Tags      []string           `json:"tags"`
	UpdatedBy string             `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListControlsPaginated(ctx context.Context, arg ListControlsPaginatedParams) ([]ListControlsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listControlsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlsPaginatedRow
	for rows.Next() {
		var i ListControlsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.Status,
			&i.Version,
			&i.Tags,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateControl = `-- name: UpdateControl :one
UPDATE controls
SET 
    title = $2,
    category = $3,
    question = $4,
    answer = $5,
    status = $6,
    version = $7,
    tags = $8,
    updated_by = $9,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, question, answer, category, tags, version, updated_by, updated_at, status
`

type UpdateControlParams struct {
	ID        string            `json:"id"`
	Title     string            `json:"title"`
	Category  string            `json:"category"`
	Question  string            `json:"question"`
	Answer    string            `json:"answer"`
	Status    NullControlStatus `json:"status"`
	Version   int32             `json:"version"`
	Tags      []string          `json:"tags"`
	UpdatedBy string            `json:"updated_by"`
}

func (q *Queries) UpdateControl(ctx context.Context, arg UpdateControlParams) (Control, error) {
	row := q.db.QueryRow(ctx, updateControl,
		arg.ID,
		arg.Title,
		arg.Category,
		arg.Question,
		arg.Answer,
		arg.Status,
		arg.Version,
		arg.Tags,
		arg.UpdatedBy,
	)
	var i Control
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Question,
		&i.Answer,
		&i.Category,
		&i.Tags,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
