// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingestions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngestion = `-- name: CreateIngestion :one
INSERT INTO ingestions (file_name, status, created_by)
VALUES ($1, $2, $3)
RETURNING id, file_name, status, error_message, created_by, created_at, updated_at
`

type CreateIngestionParams struct {
	FileName  string `json:"file_name"`
	Status    string `json:"status"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) CreateIngestion(ctx context.Context, arg CreateIngestionParams) (Ingestion, error) {
	row := q.db.QueryRow(ctx, createIngestion, arg.FileName, arg.Status, arg.CreatedBy)
	var i Ingestion
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIngestions = `-- name: ListIngestions :many
SELECT id, file_name, status, error_message, created_by, created_at, updated_at FROM ingestions
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListIngestions(ctx context.Context) ([]Ingestion, error) {
	rows, err := q.db.Query(ctx, listIngestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingestion
	for rows.Next() {
		var i Ingestion
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngestionStatus = `-- name: UpdateIngestionStatus :exec
UPDATE ingestions
SET status = $2, error_message = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateIngestionStatusParams struct {
	ID           int32       `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateIngestionStatus(ctx context.Context, arg UpdateIngestionStatusParams) error {
	_, err := q.db.Exec(ctx, updateIngestionStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
