// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ControlStatus string

const (
	ControlStatusDraft     ControlStatus = "draft"
	ControlStatusActive    ControlStatus = "active"
	ControlStatusArchived  ControlStatus = "archived"
	ControlStatusCompleted ControlStatus = "completed"
)

func (e *ControlStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ControlStatus(s)
	case string:
		*e = ControlStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ControlStatus: %T", src)
	}
	return nil
}

type NullControlStatus struct {
	ControlStatus ControlStatus `json:"control_status"`
	Valid         bool          `json:"valid"` // Valid is true if ControlStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullControlStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ControlStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ControlStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullControlStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ControlStatus), nil
}

type FeedEventType string

const (
	FeedEventTypeCreated FeedEventType = "created"
	FeedEventTypeUpdated FeedEventType = "updated"
	FeedEventTypeMapped  FeedEventType = "mapped"
)

func (e *FeedEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedEventType(s)
	case string:
		*e = FeedEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedEventType: %T", src)
	}
	return nil
}

type NullFeedEventType struct {
	FeedEventType FeedEventType `json:"feed_event_type"`
	Valid         bool          `json:"valid"` // Valid is true if FeedEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedEventType) Scan(value interface{}) error {
	if value == nil {
		ns.FeedEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedEventType), nil
}

type UnmatchedStatus string

const (
	UnmatchedStatusPending  UnmatchedStatus = "pending"
	UnmatchedStatusResolved UnmatchedStatus = "resolved"
	UnmatchedStatusIgnored  UnmatchedStatus = "ignored"
)

func (e *UnmatchedStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnmatchedStatus(s)
	case string:
		*e = UnmatchedStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UnmatchedStatus: %T", src)
	}
	return nil
}

type NullUnmatchedStatus struct {
	UnmatchedStatus UnmatchedStatus `json:"unmatched_status"`
	Valid           bool            `json:"valid"` // Valid is true if UnmatchedStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnmatchedStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UnmatchedStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnmatchedStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnmatchedStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnmatchedStatus), nil
}

type Control struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Question  string             `json:"question"`
	Answer    string             `json:"answer"`
	Category  string             `json:"category"`
	Tags      []string           `json:"tags"`
	Version   int32              `json:"version"`
	UpdatedBy string             `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Status    NullControlStatus  `json:"status"`
}

type ControlVersion struct {
	ControlID string             `json:"control_id"`
	Version   int32              `json:"version"`
	Snapshot  []byte             `json:"snapshot"`
	Diff      []byte             `json:"diff"`
	ChangedBy string             `json:"changed_by"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

type FeedEvent struct {
	ID          int32              `json:"id"`
	EventType   FeedEventType      `json:"event_type"`
	ControlID   pgtype.Text        `json:"control_id"`
	UserName    string             `json:"user_name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Ingestion struct {
	ID           int32              `json:"id"`
	FileName     string             `json:"file_name"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedBy    string             `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UnmatchedTask struct {
	ID               int32               `json:"id"`
	OriginalFileName string              `json:"original_file_name"`
	RowNumber        int32               `json:"row_number"`
	QuestionText     string              `json:"question_text"`
	Status           NullUnmatchedStatus `json:"status"`
	CreatedAt        pgtype.Timestamptz  `json:"created_at"`
	ResolvedAt       pgtype.Timestamptz  `json:"resolved_at"`
}
