// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchControls = `-- name: SearchControls :many
SELECT 
    id, title, category, question, answer, status, version, tags, updated_by, updated_at
FROM controls
WHERE 
    (title || ' ' || question || ' ' || answer) ILIKE '%' || $1 || '%'
ORDER BY updated_at DESC
`

type SearchControlsRow struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Question  string             `json:"question"`
	Answer    string             `json:"answer"`
	Status    NullControlStatus  `json:"status"`
	Version   int32              `json:"version"`
	Tags      []string           `json:"tags"`
	UpdatedBy string             `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SearchControls(ctx context.Context, dollar_1 pgtype.Text) ([]SearchControlsRow, error) {
	rows, err := q.db.Query(ctx, searchControls, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchControlsRow
	for rows.Next() {
		var i SearchControlsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.Status,
			&i.Version,
			&i.Tags,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
